---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: deploy
  become: true
  become_user: root
  become_method: sudo
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    notify:
      - openfirewallrules
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  - name: openfirewallrules
    firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted        
